"""add_session_indexes

Revision ID: d4940e4bda2d
Revises: b83b2a688072
Create Date: 2026-01-26 14:24:44.563345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4940e4bda2d'
down_revision: Union[str, None] = 'b83b2a688072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 만료 세션 정리 크론잡 최적화 인덱스
    op.create_index(
        'idx_refresh_token_cleanup',
        'auth_refresh_token',
        ['last_activity_at'],
        unique=False,
        postgresql_where=sa.text("revoked_yn = 'N'")
    )
    
    # 2. 활성 세션 조회 및 동시접속 체크 최적화 인덱스
    op.create_index(
        'idx_refresh_token_user_active',
        'auth_refresh_token',
        ['user_id', 'revoked_yn', 'last_activity_at'],
        unique=False,
        postgresql_where=sa.text("revoked_yn = 'N'")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'idx_refresh_token_user_active',
        table_name='auth_refresh_token',
        postgresql_where=sa.text("revoked_yn = 'N'")
    )
    op.drop_index(
        'idx_refresh_token_cleanup',
        table_name='auth_refresh_token',
        postgresql_where=sa.text("revoked_yn = 'N'")
    )
    # ### end Alembic commands ###
